name: apne_saathi_app
description: Secure member directory MVP for Android-first internal distribution.
publish_to: 'none'

version: 0.1.2+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  image_picker: ^1.1.2
  local_auth: ^3.0.1
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2
  vibration: ^3.1.3
  http: ^1.2.2
  qr_flutter: ^4.1.0
  share_plus: ^12.0.1
  geolocator: ^14.0.2
  shared_preferences: ^2.3.2
  device_info_plus: ^10.1.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - police_station_list.csv
    - logos/logo2.png
    - logos/logo1.webp